services:
  - type: web
    name: smart-ingredient-analyzer-api
    env: python
    region: oregon
    buildCommand: "cd Smart-Ingredient-Analyzer/backend && pip install -r requirements.txt && apt-get update && apt-get install -y tesseract-ocr"
    startCommand: "cd Smart-Ingredient-Analyzer/backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: PORT
        value: 10000
